<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <AssemblyName>nexIRC.Desktop</AssemblyName>
    <RootNamespace>nexIRC.Desktop</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\nexIRC.Application\nexIRC.Application.csproj" />
    <ProjectReference Include="..\nexIRC.Networking\nexIRC.Networking.csproj" />
  </ItemGroup>
</Project>
